spring:
  datasource:
    url: jdbc:mysql:///jobspring?cloudSqlInstance=${CLOUD_SQL_CONNECTION_NAME}&socketFactory=com.google.cloud.sql.mysql.SocketFactory&user=${DB_USER}&password=${DB_PASS}&characterEncoding=utf8
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate.ddl-auto: validate
    open-in-view: false
    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
server.port: ${PORT:8080}