name: CI - Backend

on:
  pull_request:
    branches: [ "main", "master" ]
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - name: Lint (Checkstyle)
        run: mvn -B checkstyle:check

      - name: Unit tests with coverage
        run: mvn -B clean verify -Ddependency-check.skip=true

      - name: Upload JaCoCo HTML
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-html
          path: target/site/jacoco/**

      - name: Upload JaCoCo XML
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-xml
          path: target/jacoco.xml


