name: CI - Backend

on:
  pull_request:
    branches: [ "main", "master" ]
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - name: Lint (Checkstyle)
        run: mvn -B checkstyle:check

      - name: Unit tests with coverage
        run: mvn -B clean verify

      - name: Assert NVD key present
        env: { NVD_API_KEY: ${ { secrets.NVD_API_KEY } } }
        run: |
          if [ -z "$NVD_API_KEY" ]; then
            echo "NVD_API_KEY is EMPTY in this job"; exit 1
          else
            echo "NVD_API_KEY is PRESENT"
          fi
      - name: Cache Dependency-Check DB
        uses: actions/cache@v4
        with:
          path: ~/.dependency-check
          key: dc-${{ runner.os }}-v1

      - name: Run SCA (Dependency-Check, no update)
        run: |
          mvn -B org.owasp:dependency-check-maven:check \
            -Dautoupdate=false \
            -DdataDirectory="$HOME/.dependency-check" \
            -Dformat=HTML -DoutputDirectory=target

      - name: Upload SCA report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: target/dependency-check-report.html

