name: CI - Backend

on:
  pull_request:
    branches: [ "main", "master" ]
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - name: Lint (Checkstyle)
        run: mvn -B checkstyle:check

      - name: Unit tests with coverage
        run: mvn -B clean verify

      - name: Purge bad cache if exists
        run: rm -rf "$HOME/.dependency-check"

      - name: Cache Dependency-Check DB
        uses: actions/cache@v4
        with:
          path: ~/.dependency-check
          key: dc-${{ runner.os }}-v1

      - name: SCA (OWASP Dependency-Check)
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: |
          mvn -B org.owasp:dependency-check-maven:check \
            -Dnvd.api.key="$NVD_API_KEY" \
            -DdataDirectory="$HOME/.dependency-check" \
            -Dformat=HTML -DoutputDirectory=target

