name: Deploy API (Cloud Run with GHCR)
on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    env:
      IMAGE: ghcr.io/${{ github.repository }}/api:${{ github.sha }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build JAR
        run: mvn -B -DskipTests package

      - uses: docker/setup-buildx-action@v3

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        run: |
          docker build -t "$IMAGE" .
          docker push "$IMAGE"

      - name: Auth to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - uses: google-github-actions/setup-gcloud@v2

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy jobspring-api \
            --region=asia-southeast1 \
            --image="$IMAGE" \
            --platform=managed \
            --allow-unauthenticated \
            --add-cloudsql-instances="${{ secrets.CLOUD_SQL_CONN }}" \
            --set-env-vars=SPRING_PROFILES_ACTIVE=prod \
            --set-env-vars=CLOUD_SQL_CONNECTION_NAME=${{ secrets.CLOUD_SQL_CONN }} \
            --set-env-vars=CORS_ALLOW_ORIGINS=${{ secrets.CORS_ALLOW_ORIGINS }} \
            --set-secrets=DB_USER=${{ secrets.DB_USER_SECRET }}:latest,DB_PASS=${{ secrets.DB_PASS_SECRET }}:latest \
            --memory=512Mi --cpu=1 --concurrency=80 --min-instances=0