name: sonar-backend

on:
  push:
    branches: [ master ]

permissions:
  contents: read

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: m2-${{ hashFiles('**/pom.xml') }}

      - name: Test + Coverage
        run: mvn -B clean verify

      - name: SonarCloud Scan
        run: |
          mvn -B org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.organization=${{ secrets.SONAR_ORG }} \
            -Dsonar.projectKey=jobspring-backend \
            -Dsonar.projectName=jobspring-backend \
            -Dsonar.qualitygate.wait=false
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml