name: sonar-backend

on:
  push:
    branches: [ master ]
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        svc: [ auth-service, company-service, job-service, application-service, gateway-service ]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: m2-${{ hashFiles('**/pom.xml') }}

      - name: Test + Coverage
        working-directory: ${{ matrix.svc }}
        run: mvn -B -DskipTests=false clean verify

      - name: SonarCloud Scan
        working-directory: ${{ matrix.svc }}
        run: |
          mvn -B org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.organization=${{ secrets.SONAR_ORG }} \
            -Dsonar.projectKey=jobspring-${{ matrix.svc }} \
            -Dsonar.projectName=${{ matrix.svc }} \
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml